/*
http://www.cgsoso.com/forum-211-1.html

CG搜搜 Unity3d 每日Unity3d插件免费更新 更有VIP资源！

CGSOSO 主打游戏开发，影视设计等CG资源素材。

插件由会员免费分享，如果商用，请务必联系原著购买授权！

daily assets update for try.

U should buy a license from author if u use it in your project!
*/

// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_daily_best = "CgkIlcKs4_UUEAIQBA"; // <GPGSID>
        public const string achievement_complete_20 = "CgkIlcKs4_UUEAIQBg"; // <GPGSID>
        public const string leaderboard_best_time = "CgkIlcKs4_UUEAIQAQ"; // <GPGSID>
        public const string achievement_complete_10 = "CgkIlcKs4_UUEAIQBQ"; // <GPGSID>
        public const string achievement_complete_100 = "CgkIlcKs4_UUEAIQCA"; // <GPGSID>
        public const string achievement_complete_50 = "CgkIlcKs4_UUEAIQBw"; // <GPGSID>

}

