/*
http://www.cgsoso.com/forum-211-1.html

CG搜搜 Unity3d 每日Unity3d插件免费更新 更有VIP资源！

CGSOSO 主打游戏开发，影视设计等CG资源素材。

插件由会员免费分享，如果商用，请务必联系原著购买授权！

daily assets update for try.

U should buy a license from author if u use it in your project!
*/

public enum AnalyticsEvents
{
	Undefined,
	MainScr_opened,
	MyWorksScr_opened,
	PhotosScr_opened,
	Image_opened,
	IapScr_opened,
	IapScr_closed,
	WeekSubscrBtn_tapped,
	MonthSubscrBtn_tapped,
	YearSubscrBtn_tapped,
	DeleteBtn_tapped,
	Delete_success,
	Interstitial_showed,
	InfoScr_opened,
	RestoreBtn_tapped,
	Purchases_restored,
	RateUs_tapped,
	MoreAppsBtn_tapped,
	HelpScr_opened,
	SupportScr_opened,
	tutorial_opened,
	tutorial_closed,
	FiltersScr_opened,
	FiltersScr_closed,
	LongTap_activated,
	ShareScr_opened,
	DeleteWatermarkBtn_tapped,
	SaveBtn_tapped,
	Save_success,
	ShareBtn_tapped,
	ShareViaFbBtn_tapped,
	ShareViaInstagramBtn_tapped,
	Element_colored,
	purchase_from_ad,
	coloring_session,
	Image_continued,
	Image_Reopened,
	BackBtn_Tapped,
	Zoom_done,
	IapScr_7d_opened,
	IapScr_7d_closed,
	Subscr_success,
	Subscr_cancel,
	Subscr_fail,
	TrialSubscr_success,
	NotTrialSubscr_success,
	Subscr_success_sandbox,
	TrialSubscr_success_sandbox,
	NotTrialSubscr_success_sandbox,
	Image_done,
	gamescreen_booster_grenade,
	gamescreen_booster_grenade_used,
	gamescreen_booster_grenade_add,
	gamescreen_booster_magicwand,
	gamescreen_booster_magicwand_used,
	gamescreen_booster_magicwand_add,
	session_1day,
	session_2ndDay,
	session_nearest2days,
	picture_completed,
	picture_completed_1st,
	picture_completed_2nd,
	picture_completed_3rd,
	picture_completed_5th,
	picture_selected,
	picture_opened,
	time_total,
	time_gamescreen,
	previous_users,
	sub_promo_displayed,
	sub_promo_action,
	sub_1option_displayed,
	sub_1option_action,
	sub_3options_displayed,
	sub_3options_action,
	sub_launch_1option_displayed,
	sub_launch_1option_action,
	sub_campaign_1option_displayed,
	sub_campaign_1option_action,
	sub_launch_week_trial,
	sub_week,
	sub_week_restore,
	sub_month,
	sub_month_restore,
	sub_year,
	sub_year_restore,
	sub_result,
	share_art,
	fire_avg_impression_7d,
	fire_avg_time_7d
}


